In [1]:
#importing the libraries
import pandas as pd
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

In [2]:

df = pd.read_csv('wine_original.csv')

# first 5 rows of the data
df.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,target
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [3]:
df.shape

(178, 14)

In [4]:
df.isnull().sum()

Alcohol                         0
Malic acid                      0
Ash                             0
Alcalinity of ash               0
Magnesium                       0
Total phenols                   0
Flavanoids                      0
Nonflavanoid phenols            0
Proanthocyanins                 0
Color intensity                 0
Hue                             0
OD280/OD315 of diluted wines    0
Proline                         0
target                          0
dtype: int64

In [6]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Alcohol, Malic acid, Ash, Alcalinity of ash, Magnesium, Total phenols, Flavanoids, Nonflavanoid phenols, Proanthocyanins, Color intensity, Hue, OD280/OD315 of diluted wines, Proline, target]
Index: []

In [7]:
X=df.iloc[:,0:13]
y=df.iloc[:,-1]

In [9]:
X.head()

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [10]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100)

from sklearn.ensemble import RandomForestClassifier

In [13]:
# only 6 feature
forward_feature_selection=sfs(RandomForestClassifier(n_jobs=-1),
                              k_features=6,
                              forward=True,
                              floating=False,
                              verbose=2,
                              scoring='accuracy',
                              cv=5
                              ).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    9.7s finished

[2022-05-19 12:11:00] Features: 1/6 -- score: 0.7823333333333333[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    6.5s finished

[2022-05-19 12:11:06] Features: 2/6 -- score: 0.9436666666666665[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    5.7s finished

[2022-05-19 12:11:12] Features: 3/6 -- score: 0.9676666666666666[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    5.5s finished

[2022-05-19 12:11:17] Features: 4/6 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    4.8s finished

[2022-05-19 12:11:22] Features: 5/6 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    4.1s finished

[2022-05-19 12:11:26] Features: 6/6 -- score: 0.984

In [14]:
forward_feature_selection.k_feature_idx_

(1, 4, 5, 6, 9, 12)

In [15]:
forward_feature_selection.k_feature_names_

('Malic acid',
 'Magnesium',
 'Total phenols',
 'Flavanoids',
 'Color intensity',
 'Proline')

In [16]:
forward_feature_selection.k_score_

0.984

In [17]:
pd.DataFrame.from_dict(forward_feature_selection.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(6,)","[0.76, 0.76, 0.8, 0.8, 0.7916666666666666]",0.782333,"(Flavanoids,)",0.023761,0.018487,0.009244
2,"(6, 12)","[0.88, 0.96, 0.96, 0.96, 0.9583333333333334]",0.943667,"(Flavanoids, Proline)",0.040924,0.031840,0.015920
3,"(6, 9, 12)","[0.92, 1.0, 0.96, 1.0, 0.9583333333333334]",0.967667,"(Flavanoids, Color intensity, Proline)",0.038597,0.030030,0.015015
4,"(1, 6, 9, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984000,"(Malic acid, Flavanoids, Color intensity, Prol...",0.025186,0.019596,0.009798
5,"(1, 5, 6, 9, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984000,"(Malic acid, Total phenols, Flavanoids, Color ...",0.025186,0.019596,0.009798
6,"(1, 4, 5, 6, 9, 12)","[0.96, 1.0, 1.0, 0.96, 1.0]",0.984000,"(Malic acid, Magnesium, Total phenols, Flavano...",0.025186,0.019596,0.009798

In [18]:
# All Features
forward_feature_selection=sfs(RandomForestClassifier(n_jobs=-1),
                              k_features=(1,13),
                              forward=True,
                              floating=False,
                              verbose=2,
                              scoring='accuracy',
                              cv=5
                              ).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:   10.1s finished

[2022-05-19 12:17:36] Features: 1/13 -- score: 0.7743333333333333[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    6.3s finished

[2022-05-19 12:17:43] Features: 2/13 -- score: 0.9433333333333334[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    5.8s finished

[2022-05-19 12:17:48] Features: 3/13 -- score: 0.9676666666666666[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    5.3s finished

[2022-05-19 12:17:54] Features: 4/13 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    4.6s finished

[2022-05-19 12:17:58] Features: 5/13 -- score: 0.976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    4.4s finished

[2022-05-19 12:18:03] Features: 6/13 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    3.9s finished

[2022-05-19 12:18:07] Features: 7/13 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    3.2s finished

[2022-05-19 12:18:10] Features: 8/13 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    2.9s finished

[2022-05-19 12:18:13] Features: 9/13 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    2.2s finished

[2022-05-19 12:18:15] Features: 10/13 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.6s finished

[2022-05-19 12:18:17] Features: 11/13 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.3s finished

[2022-05-19 12:18:18] Features: 12/13 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s finished

[2022-05-19 12:18:18] Features: 13/13 -- score: 0.984

In [19]:
forward_feature_selection.k_feature_idx_

(0, 3, 4, 6, 9, 12)

In [20]:
forward_feature_selection.k_feature_names_

('Alcohol',
 'Alcalinity of ash',
 'Magnesium',
 'Flavanoids',
 'Color intensity',
 'Proline')

In [21]:
forward_feature_selection.k_feature_names_

('Alcohol',
 'Alcalinity of ash',
 'Magnesium',
 'Flavanoids',
 'Color intensity',
 'Proline')

In [22]:
forward_feature_selection.k_score_

0.992

In [23]:
pd.DataFrame.from_dict(forward_feature_selection.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(6,)","[0.76, 0.76, 0.76, 0.8, 0.7916666666666666]",0.774333,"(Flavanoids,)",0.022816,0.017751,0.008876
2,"(6, 9)","[0.96, 0.96, 1.0, 0.88, 0.9166666666666666]",0.943333,"(Flavanoids, Color intensity)",0.052959,0.041204,0.020602
3,"(6, 9, 12)","[0.92, 1.0, 0.96, 1.0, 0.9583333333333334]",0.967667,"(Flavanoids, Color intensity, Proline)",0.038597,0.030030,0.015015
4,"(0, 6, 9, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984000,"(Alcohol, Flavanoids, Color intensity, Proline)",0.025186,0.019596,0.009798
5,"(0, 3, 6, 9, 12)","[0.96, 0.96, 0.96, 1.0, 1.0]",0.976000,"(Alcohol, Alcalinity of ash, Flavanoids, Color...",0.025186,0.019596,0.009798
6,"(0, 3, 4, 6, 9, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992000,"(Alcohol, Alcalinity of ash, Magnesium, Flavan...",0.020565,0.016000,0.008000
7,"(0, 2, 3, 4, 6, 9, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992000,"(Alcohol, Ash, Alcalinity of ash, Magnesium, F...",0.020565,0.016000,0.008000
8,"(0, 1, 2, 3, 4, 6, 9, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992000,"(Alcohol, Malic acid, Ash, Alcalinity of ash, ...",0.020565,0.016000,0.008000
9,"(0, 1, 2, 3, 4, 5, 6, 9, 12)","[0.96, 0.96, 1.0, 1.0, 1.0]",0.984000,"(Alcohol, Malic acid, Ash, Alcalinity of ash, ...",0.025186,0.019596,0.009798
10,"(0, 1, 2, 3, 4, 5, 6, 9, 10, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992000,"(Alcohol, Malic acid, Ash, Alcalinity of ash, ...",0.020565,0.016000,0.008000
11,"(0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 12)","[0.96, 0.96, 1.0, 1.0, 1.0]",0.984000,"(Alcohol, Malic acid, Ash, Alcalinity of ash, ...",0.025186,0.019596,0.009798
12,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984000,"(Alcohol, Malic acid, Ash, Alcalinity of ash, ...",0.025186,0.019596,0.009798
13,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984000,"(Alcohol, Malic acid, Ash, Alcalinity of ash, ...",0.025186,0.019596,0.009798